### PR TITLE
[experimental] rattler

### PR DESCRIPTION
**Pull request by moritzwilksch**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by moritzwilksch** [comment]
@wolfv it seems like
1) rattler is invoked without the `-m` variant flag here (linux_64 build)
2) in the `linux_aarch64` the target platform looks sus 👀

**Comment by moritzwilksch** [comment]
@conda-forge-admin, please restart ci

**Comment by moritzwilksch** [comment]
@wolfv do the changes in `conda-forge-ci-setup-feedstock` deploy from main or how can I try whether this fixed the issue here?

**Comment by wolfv** [comment]
Right now you seem to have a conflict with `meta.yaml`. If you re-render things should theoretically work (if there are no other rattler-build specific issues!) :)

**Comment by moritzwilksch** [comment]
thank you that fixed the original problem! Target platform detection also seems to work but now there's a new error for aarch64 and ppc64le:

`FileNotFoundError: [Errno 2] No such file or directory: '/home/conda/feedstock_root/build_artifacts/linux-aarch64'`

**Comment by wolfv** [comment]
I think the problem is that we need to fix `conda-smithy` for cross-compilation with rattler-build. The target platform needs to be passed explicitly on the command line (not as part of the variant config). I'll try to get to it tomorrow :)

**Comment by moritzwilksch** [comment]
amazing! As always, `rattler-build` is a joy to use, thank you so much for building it 🙃😍

**Comment by wolfv** [comment]
Pushed rerender with a development version of `conda-smithy` to check wether things migth be fixed :)

**Comment by wolfv** [comment]
Alright, now we're hitting different issues! 🚀 
I need to figure out what to do with the `__osx` package on osx-arm64 :)

**Comment by moritzwilksch** [comment]
@conda-forge-admin, please rerender

**Comment by moritzwilksch** [comment]
superseded by #184

**Pull request closed without merging**
