### PR TITLE
fix: ship `pyright` npm package to make conda package self-contained

### PR DESCRIPTION
**Pull request by moritzwilksch**
currently, this conda package does not ship with the `pyright` npm package containing the typescript code that is necessary to run `pyright`. This package is [downloaded after first invocation during runtime](https://github.com/RobertCraigie/pyright-python/blob/276e381d86df9da5a240f966107f485e594bc64a/src/pyright/_utils.py#L28-L73). Unfortunately, that means that one cannot use the `pyright` conda package on systems without an internet connection as it is not self-contained. My fix here invokes `pyright` during the build phase to trigger the download. This should result in a self-contained conda package.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by moritzwilksch** [comment]
@conda-forge-admin, please rerender!

**Comment by thewchan** [comment]
Thanks @moritzwilksch; I understand your intention but I'm not 100% familiar with the implementation. I'm pinging @conda-forge/core team just for a quick glance through in case there are any concerns?

**Comment by moritzwilksch** [comment]
ahh we might need to manually install the npm pyright to a different location. Browsing through the code it seems like it would land in `$XDG_CACHE_HOME/pyright-python/version/`

**Comment by moritzwilksch** [comment]
we could set `PYRIGHT_PYTHON_CACHE_DIR=$PREFIX/lib` to have it install `node_modules` into the package itself. Unfortunately that would still require the user to set `PYRIGHT_PYTHON_CACHE_DIR` during runtime because by default `pyright-python` only checks for pyright in the default cache directory 🥲 Wdyt is a sensible option here?

**Comment by xhochy** [comment]
You can add setting that variable to an activation script.

Also you need to bundle all licenses of the `npm` dependencies like in other NodeJS packages.

**Pull request closed without merging**
